/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tìm kiếm & xếp hạng nhà hàng
         * @description Nhận nhu cầu bằng ngôn ngữ tự nhiên kèm ràng buộc, trả danh sách đã xếp hạng.
         *
         *     Mỗi kết quả kèm `suggested_dish` (Lớp 5 của đề án) - gợi ý MÓN đi liền với quán, thay
         *     vì bắt client gọi thêm một endpoint khác và tự ghép hai danh sách.
         */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Restaurant Detail
         * @description Chi tiết 1 quán: giá, review thật, ảnh, không gian, giờ mở cửa.
         *
         *     `restaurant_id` lấy từ field `restaurant_id` trong kết quả của POST /api/v1/search.
         *
         *     Quán chưa cào được chi tiết trả 200 kèm `has_details: false` (KHÔNG phải 404) - quán
         *     vẫn tồn tại và vẫn được đề xuất, chỉ là chưa có dữ liệu bổ sung.
         */
        get: operations["restaurant_detail_api_v1_restaurants__restaurant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Interaction
         * @description Ghi một sự kiện tương tác gắn với một nhà hàng cụ thể.
         *
         *     `is_positive_signal` được tính Ở SERVER theo quy tắc thống nhất, không để client tự
         *     suy luận - nếu không, nhãn huấn luyện sẽ nhiễu.
         */
        post: operations["log_interaction_api_v1_interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Moods
         * @description Các mood dùng cho lối tắt `mood` của POST /search.
         *
         *     Đề án ưu tiên tìm kiếm bằng câu tự do; danh sách này chỉ phục vụ nút bấm nhanh.
         */
        get: operations["moods_api_v1_moods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Đổi tài khoản/mật khẩu lấy token ngắn hạn.
         *
         *     Sai thông tin -> 401 UNAUTHORIZED. Chưa cấu hình admin -> 503 kèm hướng dẫn.
         */
        post: operations["login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Restaurants
         * @description Danh sách quán cho trang quản trị.
         *
         *     MẶC ĐỊNH có cả quán đã ẩn — khác với `/search` của người dùng cuối. Không có nó thì
         *     ẩn xong sẽ không còn cách nào tìm lại để bỏ ẩn.
         */
        get: operations["list_restaurants_api_v1_admin_restaurants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Restaurant
         * @description Sửa các trường mô tả của một quán.
         *
         *     `exclude_unset=True`: chỉ gửi trường nào thì sửa trường đó. Nhờ vậy client phân biệt
         *     được "không đụng tới trường này" với "xoá giá trị của trường này" (gửi `null`).
         */
        patch: operations["update_restaurant_api_v1_admin_restaurants__restaurant_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/restaurants/{restaurant_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hide Restaurant
         * @description Ẩn quán (soft-delete). Dữ liệu KHÔNG bị xoá, chỉ biến mất khỏi luồng người dùng.
         */
        post: operations["hide_restaurant_api_v1_admin_restaurants__restaurant_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants/{restaurant_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Restaurant
         * @description Bỏ ẩn quán đã ẩn.
         */
        post: operations["restore_restaurant_api_v1_admin_restaurants__restaurant_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "view_detail" | "get_directions" | "save" | "explicit_positive" | "explicit_negative";
        /** AdminLoginData */
        AdminLoginData: {
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Số giây token còn hiệu lực
             */
            expires_in: number;
        };
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            data: components["schemas"]["AdminLoginData"];
        };
        /** AdminRestaurantListData */
        AdminRestaurantListData: {
            /** Total */
            total: number;
            /** Results */
            results: components["schemas"]["AdminRestaurantSummary"][];
        };
        /** AdminRestaurantListResponse */
        AdminRestaurantListResponse: {
            data: components["schemas"]["AdminRestaurantListData"];
        };
        /** AdminRestaurantResponse */
        AdminRestaurantResponse: {
            data: components["schemas"]["AdminRestaurantSummary"];
        };
        /**
         * AdminRestaurantSummary
         * @description Một quán nhìn từ phía quản trị.
         *
         *     `rating`/`reviews_count`/`price` để None khi CHƯA CÓ DỮ LIỆU — không đổi thành 0
         *     hay chuỗi rỗng, vì admin cần phân biệt "thiếu dữ liệu" với "giá trị bằng 0".
         */
        AdminRestaurantSummary: {
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /**
             * Price
             * @description Chuỗi khoảng giá, VD "1-100.000 ₫"
             */
            price?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Rating */
            rating?: number | null;
            /** Reviews Count */
            reviews_count?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Source */
            source?: string | null;
        };
        /**
         * AdminUpdateRestaurantRequest
         * @description Chỉ những trường được gửi lên mới bị sửa (`exclude_unset=True` ở router).
         *
         *     Gửi `null` = XOÁ giá trị. Không gửi trường = giữ nguyên. Đây là hai ý định khác
         *     nhau nên không được gộp làm một.
         */
        AdminUpdateRestaurantRequest: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /**
             * Price
             * @description CHUỖI, không phải số
             */
            price?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Status */
            status: string;
            /** Api Version */
            api_version: string;
            /** Services */
            services: {
                [key: string]: unknown;
            };
        };
        /** HealthResponse */
        HealthResponse: {
            data: components["schemas"]["HealthData"];
        };
        /** InteractionRequest */
        InteractionRequest: {
            /** Session Id */
            session_id: string;
            /** Restaurant Id */
            restaurant_id: string;
            action_type: components["schemas"]["ActionType"];
            /** Search Query Id */
            search_query_id?: string | null;
            /**
             * Dwell Time Ms
             * @description Bắt buộc khi action_type = view_detail.
             */
            dwell_time_ms?: number | null;
            /** Rank Position */
            rank_position?: number | null;
        };
        /** InteractionResponse */
        InteractionResponse: {
            data: components["schemas"]["InteractionResponseData"];
        };
        /** InteractionResponseData */
        InteractionResponseData: {
            /** Interaction Event Id */
            interaction_event_id: string;
            /** Is Positive Signal */
            is_positive_signal: boolean;
        };
        /** MoodsData */
        MoodsData: {
            /** Supported Moods */
            supported_moods: string[];
            /** Description */
            description: string;
        };
        /** MoodsResponse */
        MoodsResponse: {
            data: components["schemas"]["MoodsData"];
        };
        /** RestaurantDetailData */
        RestaurantDetailData: {
            /** Restaurant Id */
            restaurant_id: string;
            /** Has Details */
            has_details: boolean;
            /** Reason */
            reason?: string | null;
            /** Name */
            name?: string | null;
            /** Price Range */
            price_range?: string | null;
            /** Atmosphere */
            atmosphere?: unknown | null;
            /** Opening Hours */
            opening_hours?: unknown | null;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Reviews
             * @default []
             */
            reviews: {
                [key: string]: unknown;
            }[];
            /** Menu Url */
            menu_url?: string | null;
            /** Website */
            website?: string | null;
            /** Google Maps Url */
            google_maps_url?: string | null;
        };
        /** RestaurantDetailResponse */
        RestaurantDetailResponse: {
            data: components["schemas"]["RestaurantDetailData"];
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Session Id
             * @description UUID v4 do client tự sinh và lưu ở localStorage. Không có tài khoản người dùng (SRS mục 8, Won't-have).
             */
            session_id: string;
            /**
             * Latitude
             * @default 21.0285
             */
            latitude: number;
            /**
             * Longitude
             * @default 105.8542
             */
            longitude: number;
            /**
             * Query Text
             * @description Nhu cầu bằng câu tự nhiên, VD "quán lẩu ấm cúng gần đây".
             */
            query_text?: string | null;
            /**
             * Mood
             * @description Lối tắt tuỳ chọn thay cho query_text. Hợp lệ: ['happy', 'sad', 'excited', 'relaxed']
             */
            mood?: string | null;
            /**
             * Max Distance Km
             * @description null = tắt lọc theo khoảng cách.
             * @default 10
             */
            max_distance_km: number | null;
            /**
             * Dietary Restrictions
             * @description vegetarian | vegan | halal | kosher | gluten_free. Dữ liệu rất thưa - quán chưa khai báo vẫn được giữ lại.
             */
            dietary_restrictions?: string[];
            /**
             * Opening Hours Constraint
             * @description "now" hoặc "HH:mm". Quán chưa có dữ liệu giờ vẫn giữ lại.
             */
            opening_hours_constraint?: string | null;
            /**
             * District
             * @description Đơn vị hành chính, VD "Phường Cầu Giấy". Không khớp quán nào -> bỏ lọc.
             */
            district?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** SearchResponse */
        SearchResponse: {
            data: components["schemas"]["SearchResponseData"];
        };
        /** SearchResponseData */
        SearchResponseData: {
            /** Search Query Id */
            search_query_id: string;
            /** Results */
            results: components["schemas"]["SearchResultItemSchema"][];
            /**
             * Context
             * @default []
             */
            context: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** SearchResultItemSchema */
        SearchResultItemSchema: {
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance M */
            distance_m: number;
            /** Price Range */
            price_range: string | null;
            /** Rating */
            rating: number | null;
            /** User Ratings Total */
            user_ratings_total: number | null;
            /** Rank Position */
            rank_position: number;
            /** Predicted Score */
            predicted_score: number;
            /** Match Source */
            match_source: string;
            /**
             * Thumbnail Url
             * @description Ảnh đại diện. null = chưa có ảnh (78.5% quán)
             */
            thumbnail_url?: string | null;
            /** District */
            district?: string | null;
            /**
             * Dietary
             * @default []
             */
            dietary: string[];
            /**
             * Amenities
             * @default []
             */
            amenities: string[];
            /** Source */
            source?: string | null;
            /** Experience Cluster Id */
            experience_cluster_id?: number | null;
            /** Experience Cluster Label */
            experience_cluster_label?: string | null;
            suggested_dish?: components["schemas"]["SuggestedDishSchema"] | null;
        };
        /** SuggestedDishSchema */
        SuggestedDishSchema: {
            /** Dish Id */
            dish_id: string;
            /** Name */
            name: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Spice Level */
            spice_level?: number | null;
            /** Temperature */
            temperature?: string | null;
            /** Confidence */
            confidence: string;
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    restaurant_detail_api_v1_restaurants__restaurant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantDetailResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    log_interaction_api_v1_interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    moods_api_v1_moods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoodsResponse"];
                };
            };
        };
    };
    login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_restaurants_api_v1_admin_restaurants_get: {
        parameters: {
            query?: {
                /** @description Lọc theo tên, địa chỉ hoặc placeId */
                q?: string | null;
                limit?: number;
                /** @description Có kèm quán đã ẩn hay không */
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_restaurant_api_v1_admin_restaurants__restaurant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateRestaurantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_restaurant_api_v1_admin_restaurants__restaurant_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_restaurant_api_v1_admin_restaurants__restaurant_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
