/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tìm kiếm & xếp hạng nhà hàng
         * @description Nhận nhu cầu bằng ngôn ngữ tự nhiên kèm ràng buộc, trả danh sách đã xếp hạng.
         *
         *     Mỗi kết quả kèm `suggested_dish` (Lớp 5 của đề án) - gợi ý MÓN đi liền với quán, thay
         *     vì bắt client gọi thêm một endpoint khác và tự ghép hai danh sách.
         */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dishes/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gợi ý MÓN theo bộ lọc + ngữ cảnh
         * @description Trang chủ: nhận bộ lọc, trả danh sách MÓN đã xếp hạng.
         *
         *     Món không có quán nào trong bán kính bị ẨN, và số món bị ẩn được nói rõ ở
         *     `data.warnings` - im lặng bỏ bớt kết quả là lỗi `/suggest-dish` cũ từng mắc.
         */
        post: operations["suggest_dishes_api_v1_dishes_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dishes/{dish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết 1 món (giới thiệu ngắn)
         * @description Giới thiệu ngắn về món + số quán bán món này gần bạn.
         *
         *     `description` rỗng kèm `has_description: false` nghĩa là CHƯA TRA ĐƯỢC nguồn nào, và
         *     giao diện phải nói đúng như vậy - không được để một khoảng trắng như thể món này không
         *     có gì để giới thiệu (CLAUDE.md mục 4 quy tắc 1).
         *
         *     Nhận toạ độ vì `restaurant_count` phải tính theo bán kính của NGƯỜI ĐANG XEM: món có
         *     1700 quán toàn thành phố nhưng 0 quán quanh đây vẫn là ngõ cụt.
         */
        get: operations["dish_detail_api_v1_dishes__dish_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dishes/{dish_id}/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quán gần đây bán món này
         * @description Danh sách quán bán món đã chọn, xếp hạng theo khoảng cách + đánh giá + ngữ cảnh.
         *
         *     Trả về ĐÚNG kiểu của `POST /search` để client dùng lại một component thẻ quán duy nhất.
         */
        get: operations["restaurants_for_dish_api_v1_dishes__dish_id__restaurants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Restaurant Detail
         * @description Chi tiết 1 quán: giá, review thật, ảnh, không gian, giờ mở cửa.
         *
         *     `restaurant_id` lấy từ field `restaurant_id` trong kết quả của POST /api/v1/search.
         *
         *     Quán chưa cào được chi tiết trả 200 kèm `has_details: false` (KHÔNG phải 404) - quán
         *     vẫn tồn tại và vẫn được đề xuất, chỉ là chưa có dữ liệu bổ sung.
         */
        get: operations["restaurant_detail_api_v1_restaurants__restaurant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Interaction
         * @description Ghi một sự kiện tương tác gắn với một nhà hàng cụ thể.
         *
         *     `is_positive_signal` được tính Ở SERVER theo quy tắc thống nhất, không để client tự
         *     suy luận - nếu không, nhãn huấn luyện sẽ nhiễu.
         *
         *     KHÁCH VẪN GỌI ĐƯỢC. Đã đăng nhập thì tương tác được gắn thêm `user_id` để đếm "lượt
         *     khám phá" cho cấp độ. `user_id` lấy TỪ TOKEN, không lấy từ body — nếu không thì ai
         *     cũng tự cộng điểm cho mình bằng cách gọi thẳng API.
         */
        post: operations["log_interaction_api_v1_interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Moods
         * @description Các mood dùng cho lối tắt `mood` của POST /search.
         *
         *     Đề án ưu tiên tìm kiếm bằng câu tự do; danh sách này chỉ phục vụ nút bấm nhanh.
         */
        get: operations["moods_api_v1_moods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Tạo tài khoản mới. Vai luôn là `user`.
         *
         *     201 CREATED chứ không phải 200: có tài nguyên mới được tạo ra.
         *     Tên đã có người dùng -> 409 USERNAME_TAKEN. Sai định dạng -> 400 INVALID_REQUEST.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Đổi tài khoản/mật khẩu lấy token.
         *
         *     Sai tên HAY sai mật khẩu đều trả CÙNG MỘT câu 401 — không nói cái nào sai, nếu không
         *     thì đây thành công cụ dò xem tên nào đã tồn tại.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Gửi thư kèm đường dẫn đặt lại mật khẩu.
         *
         *     ⚠️ LUÔN TRẢ CÙNG MỘT CÂU, dù tài khoản có tồn tại hay không, dù có email hay không.
         *     Trả lời khác nhau là biến endpoint này thành công cụ dò xem email/tên nào đã đăng ký —
         *     đúng thứ mà `/login` đã cẩn thận tránh.
         *
         *     Giới hạn tần suất CHẶT hơn đăng nhập: mỗi lần gọi là một lá thư thật bay đi, và hạn
         *     mức SMTP miễn phí của Gmail chỉ khoảng 500 thư/ngày. Không chặn thì một người bấm liên
         *     tục là đủ làm tính năng chết cả ngày cho mọi người.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Đổi mật khẩu bằng token trong thư.
         *
         *     Token hỏng/hết hạn/đã dùng -> 401. Mật khẩu mới sai định dạng -> 400.
         *     Đổi xong KHÔNG tự đăng nhập: client phải chuyển sang trang đăng nhập.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Đổi mật khẩu khi ĐANG đăng nhập. Khác `/reset-password` (dùng token trong thư).
         *
         *     Vẫn phải nhập mật khẩu HIỆN TẠI dù đã có token — xem `ChangePasswordUseCase`.
         *     Giới hạn tần suất dùng chung bộ đếm với đăng nhập: đây cũng là chỗ đoán mật khẩu được.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Thông tin tài khoản đang đăng nhập, kèm VAI hiện tại.
         *
         *     Frontend gọi endpoint này lúc mở app để biết token còn sống không và được vào những
         *     đâu. Vai đọc từ CSDL chứ không lấy trong token, nên admin vừa bị hạ quyền sẽ thấy
         *     ngay ở lần gọi kế tiếp.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Favorites
         * @description Danh sách quán & món đã lưu của chính chủ, MỚI NHẤT ĐỨNG ĐẦU.
         */
        get: operations["list_favorites_api_v1_me_favorites_get"];
        put?: never;
        /**
         * Save Favorite
         * @description Lưu một quán hoặc một món.
         *
         *     Lưu lại thứ đã lưu KHÔNG phải lỗi — chỉ cập nhật tên và giữ nguyên thứ tự. Người dùng
         *     bấm tim hai lần vì mạng chậm không đáng nhận một thông báo lỗi.
         */
        post: operations["save_favorite_api_v1_me_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/favorites/{item_type}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Favorite
         * @description Bỏ lưu.
         *
         *     Bỏ thứ vốn không có trong danh sách vẫn trả 200. Đây là thao tác ĐƯA VỀ TRẠNG THÁI
         *     MONG MUỐN ("tôi không muốn lưu cái này nữa") — kết quả cuối cùng giống hệt nhau, nên
         *     404 chỉ làm client phải viết thêm nhánh xử lý cho một tình huống vô hại.
         */
        delete: operations["remove_favorite_api_v1_me_favorites__item_type___item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User Stats
         * @description Số liệu hoạt động + cấp độ + huy hiệu của chính chủ.
         *
         *     Tài khoản mới thì MỌI SỐ ĐỀU LÀ 0 và cấp là 1 — đó là sự thật, và giao diện phải hiện
         *     đúng như vậy. Bản thiết kế vẽ "320/500 điểm" chỉ là minh hoạ.
         */
        get: operations["user_stats_api_v1_me_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Đổi tài khoản/mật khẩu lấy token ngắn hạn.
         *
         *     Sai thông tin -> 401 UNAUTHORIZED. Chưa cấu hình admin -> 503 kèm hướng dẫn.
         */
        post: operations["login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Restaurants
         * @description Danh sách quán cho trang quản trị.
         *
         *     MẶC ĐỊNH có cả quán đã ẩn — khác với `/search` của người dùng cuối. Không có nó thì
         *     ẩn xong sẽ không còn cách nào tìm lại để bỏ ẩn.
         */
        get: operations["list_restaurants_api_v1_admin_restaurants_get"];
        put?: never;
        /**
         * Create Restaurant
         * @description Thêm một quán hoàn toàn mới.
         *
         *     201 CREATED chứ không phải 200: có tài nguyên mới được tạo ra.
         *     `place_id` do SERVER sinh với tiền tố `manual:` — nhìn mã là biết quán này do người
         *     gõ vào chứ không phải từ Google/OSM/Overture. Client KHÔNG được tự đặt mã.
         *
         *     Toạ độ ngoài Hà Nội -> 400 (phạm vi dự án chốt 2026-08-19).
         */
        post: operations["create_restaurant_api_v1_admin_restaurants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Restaurant
         * @description Sửa các trường mô tả của một quán.
         *
         *     `exclude_unset=True`: chỉ gửi trường nào thì sửa trường đó. Nhờ vậy client phân biệt
         *     được "không đụng tới trường này" với "xoá giá trị của trường này" (gửi `null`).
         */
        patch: operations["update_restaurant_api_v1_admin_restaurants__restaurant_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/restaurants/{restaurant_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hide Restaurant
         * @description Ẩn quán (soft-delete). Dữ liệu KHÔNG bị xoá, chỉ biến mất khỏi luồng người dùng.
         */
        post: operations["hide_restaurant_api_v1_admin_restaurants__restaurant_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants/{restaurant_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Restaurant
         * @description Bỏ ẩn quán đã ẩn.
         */
        post: operations["restore_restaurant_api_v1_admin_restaurants__restaurant_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "view_detail" | "get_directions" | "save" | "explicit_positive" | "explicit_negative" | "report_closed";
        /**
         * AdminCreateRestaurantRequest
         * @description Thêm quán MỚI bằng tay.
         *
         *     Chỉ `name` + `lat` + `lng` là bắt buộc — đúng ba trường thiết yếu; thiếu là bản ghi
         *     vô dụng. Mọi trường khác điền được tới đâu thì điền, để trống là `null` (CHƯA CÓ
         *     DỮ LIỆU), tuyệt đối không tự điền giá trị mặc định cho có.
         *
         *     ⚠️ KHÔNG có `rating`, `reviews_count`, `mood_scores`: chúng do nguồn thu thập hoặc do
         *     pipeline tính. Gõ tay vào là làm sai lệch chính những con số dùng để xếp hạng.
         *     Giới hạn toạ độ trong Hà Nội kiểm ở tầng domain, không kiểm ở đây.
         */
        AdminCreateRestaurantRequest: {
            /** Name */
            name: string;
            /**
             * Lat
             * @description Vĩ độ, ví dụ 21.0285. Phải nằm trong Hà Nội.
             */
            lat: number;
            /**
             * Lng
             * @description Kinh độ, ví dụ 105.8542.
             */
            lng: number;
            /**
             * Category
             * @description Để trống -> "Nhà hàng"
             */
            category?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /**
             * Price
             * @description CHUỖI khoảng giá, không phải số
             */
            price?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
        };
        /** AdminLoginData */
        AdminLoginData: {
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Số giây token còn hiệu lực
             */
            expires_in: number;
        };
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            data: components["schemas"]["AdminLoginData"];
        };
        /** AdminRestaurantListData */
        AdminRestaurantListData: {
            /** Total */
            total: number;
            /** Results */
            results: components["schemas"]["AdminRestaurantSummary"][];
        };
        /** AdminRestaurantListResponse */
        AdminRestaurantListResponse: {
            data: components["schemas"]["AdminRestaurantListData"];
        };
        /** AdminRestaurantResponse */
        AdminRestaurantResponse: {
            data: components["schemas"]["AdminRestaurantSummary"];
        };
        /**
         * AdminRestaurantSummary
         * @description Một quán nhìn từ phía quản trị.
         *
         *     `rating`/`reviews_count`/`price` để None khi CHƯA CÓ DỮ LIỆU — không đổi thành 0
         *     hay chuỗi rỗng, vì admin cần phân biệt "thiếu dữ liệu" với "giá trị bằng 0".
         */
        AdminRestaurantSummary: {
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /**
             * Price
             * @description Chuỗi khoảng giá, VD "1-100.000 ₫"
             */
            price?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Rating */
            rating?: number | null;
            /** Reviews Count */
            reviews_count?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Source */
            source?: string | null;
        };
        /**
         * AdminUpdateRestaurantRequest
         * @description Chỉ những trường được gửi lên mới bị sửa (`exclude_unset=True` ở router).
         *
         *     Gửi `null` = XOÁ giá trị. Không gửi trường = giữ nguyên. Đây là hai ý định khác
         *     nhau nên không được gộp làm một.
         */
        AdminUpdateRestaurantRequest: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /**
             * Price
             * @description CHUỖI, không phải số
             */
            price?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
        };
        /** AuthData */
        AuthData: {
            user: components["schemas"]["UserPublic"];
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Số giây token còn hiệu lực
             */
            expires_in: number;
        };
        /** AuthResponse */
        AuthResponse: {
            data: components["schemas"]["AuthData"];
        };
        /** BadgeSchema */
        BadgeSchema: {
            /** Badge Id */
            badge_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Emoji */
            emoji: string;
            /** Target */
            target: number;
            /** Current */
            current: number;
            /** Earned */
            earned: boolean;
        };
        /**
         * ChangePasswordRequest
         * @description Đổi mật khẩu khi ĐANG đăng nhập.
         *
         *     Vẫn đòi mật khẩu hiện tại dù đã có token — xem `ChangePasswordUseCase`.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** DishDetailResponse */
        DishDetailResponse: {
            data: components["schemas"]["DishItemSchema"];
        };
        /** DishItemSchema */
        DishItemSchema: {
            /** Dish Id */
            dish_id: string;
            /** Name */
            name: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Spice Level */
            spice_level?: number | null;
            /** Temperature */
            temperature?: string | null;
            /** Cooking Method */
            cooking_method?: string | null;
            /**
             * Meal Times
             * @default []
             */
            meal_times: string[];
            /**
             * Has Description
             * @default false
             */
            has_description: boolean;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Restaurant Count */
            restaurant_count: number;
            /** Rank Position */
            rank_position: number;
            /** Score */
            score: number;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Source */
            source?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Data Confidence */
            data_confidence?: string | null;
        };
        /** DishSuggestRequest */
        DishSuggestRequest: {
            /**
             * Session Id
             * @description Giống SearchRequest - định danh một LƯỢT DÙNG.
             */
            session_id: string;
            /**
             * Latitude
             * @default 21.0285
             */
            latitude: number;
            /**
             * Longitude
             * @default 105.8542
             */
            longitude: number;
            /**
             * Cooking Methods
             * @description Cách chế biến. Hợp lệ: ['nuong', 'chien', 'luoc', 'hap', 'xao', 'nuoc', 'song', 'tron', 'nuong_lo']. Món CHƯA khai cách chế biến vẫn được giữ (chưa biết ≠ không phải).
             */
            cooking_methods?: string[];
            /**
             * Temperatures
             * @description "hot" | "cold" | "room".
             */
            temperatures?: string[];
            /**
             * Cuisines
             * @description VD ["Việt Nam", "Nhật Bản"].
             */
            cuisines?: string[];
            /**
             * Meal Times
             * @description Hợp lệ: ['sang', 'trua', 'toi', 'khuya', 'an_vat'].
             */
            meal_times?: string[];
            /**
             * Max Spice Level
             * @description Mức cay TỐI ĐA chấp nhận được.
             */
            max_spice_level?: number | null;
            /**
             * Mood
             * @description Hợp lệ: ['happy', 'sad', 'excited', 'relaxed']
             */
            mood?: string | null;
            /**
             * Weather
             * @description Người dùng TỰ khai ("rain"|"clear"|"cloudy"), ghi đè số đo tự động. Người đang đứng ngoài đường biết rõ hơn API thời tiết.
             */
            weather?: string | null;
            /**
             * Max Distance Km
             * @description null = tắt lọc khoảng cách. Ảnh hưởng tới `restaurant_count`.
             * @default 10
             */
            max_distance_km: number | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** DishSuggestResponse */
        DishSuggestResponse: {
            data: components["schemas"]["DishSuggestResponseData"];
        };
        /** DishSuggestResponseData */
        DishSuggestResponseData: {
            /** Search Query Id */
            search_query_id: string;
            /** Results */
            results: components["schemas"]["DishItemSchema"][];
            /**
             * Context
             * @default []
             */
            context: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FavoritesData */
        FavoritesData: {
            /** Items */
            items: components["schemas"]["SavedItemSchema"][];
            /** Total */
            total: number;
        };
        /** FavoritesResponse */
        FavoritesResponse: {
            data: components["schemas"]["FavoritesData"];
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Identifier
             * @description Email HOẶC tên đăng nhập. Người dùng thường chỉ nhớ một trong hai.
             */
            identifier: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Status */
            status: string;
            /** Api Version */
            api_version: string;
            /** Services */
            services: {
                [key: string]: unknown;
            };
        };
        /** HealthResponse */
        HealthResponse: {
            data: components["schemas"]["HealthData"];
        };
        /** InteractionRequest */
        InteractionRequest: {
            /** Session Id */
            session_id: string;
            /** Restaurant Id */
            restaurant_id: string;
            action_type: components["schemas"]["ActionType"];
            /** Search Query Id */
            search_query_id?: string | null;
            /**
             * Dwell Time Ms
             * @description Bắt buộc khi action_type = view_detail.
             */
            dwell_time_ms?: number | null;
            /** Rank Position */
            rank_position?: number | null;
        };
        /** InteractionResponse */
        InteractionResponse: {
            data: components["schemas"]["InteractionResponseData"];
        };
        /** InteractionResponseData */
        InteractionResponseData: {
            /** Interaction Event Id */
            interaction_event_id: string;
            /** Is Positive Signal */
            is_positive_signal: boolean;
        };
        /** LevelProgressSchema */
        LevelProgressSchema: {
            current: components["schemas"]["LevelSchema"];
            next?: components["schemas"]["LevelSchema"] | null;
            /** Points */
            points: number;
            /**
             * Points To Next
             * @description null khi đã ở cấp cao nhất.
             */
            points_to_next?: number | null;
            /**
             * Ratio
             * @description [0,1] — tiến độ TRONG khoảng giữa hai cấp.
             */
            ratio: number;
        };
        /** LevelSchema */
        LevelSchema: {
            /** Number */
            number: number;
            /** Name */
            name: string;
            /** Min Points */
            min_points: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            data: components["schemas"]["UserSelf"];
        };
        /**
         * MessageData
         * @description Kết quả cho các thao tác không trả về tài nguyên nào.
         */
        MessageData: {
            /**
             * Message
             * @description Câu thông báo hiển thị thẳng cho người dùng.
             */
            message: string;
        };
        /** MessageResponse */
        MessageResponse: {
            data: components["schemas"]["MessageData"];
        };
        /** MoodsData */
        MoodsData: {
            /** Supported Moods */
            supported_moods: string[];
            /** Description */
            description: string;
        };
        /** MoodsResponse */
        MoodsResponse: {
            data: components["schemas"]["MoodsData"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Username
             * @description 3-32 ký tự, chỉ chữ thường không dấu (a-z), số, gạch dưới, gạch ngang. Tự chuẩn hoá về chữ thường.
             */
            username: string;
            /**
             * Password
             * @description Tối thiểu 8 ký tự. Không bắt buộc hoa/số/ký tự đặc biệt — độ dài quan trọng hơn (NIST SP 800-63B).
             */
            password: string;
            /**
             * Display Name
             * @description Tên hiển thị, ĐƯỢC dùng tiếng Việt có dấu. Không dùng để đăng nhập.
             */
            display_name?: string | null;
            /**
             * Email
             * @description TUỲ CHỌN. Chỉ dùng để gửi thư đặt lại mật khẩu. Không khai thì tài khoản vẫn dùng bình thường, chỉ là sau này không tự lấy lại mật khẩu được.
             */
            email?: string | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Token
             * @description Token lấy từ đường dẫn trong thư.
             */
            token: string;
            /**
             * New Password
             * @description Mật khẩu mới, tối thiểu 8 ký tự.
             */
            new_password: string;
        };
        /** RestaurantDetailData */
        RestaurantDetailData: {
            /** Restaurant Id */
            restaurant_id: string;
            /** Has Details */
            has_details: boolean;
            /** Reason */
            reason?: string | null;
            /** Name */
            name?: string | null;
            /** Price Range */
            price_range?: string | null;
            /** Atmosphere */
            atmosphere?: unknown | null;
            /** Opening Hours */
            opening_hours?: unknown | null;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Reviews
             * @default []
             */
            reviews: {
                [key: string]: unknown;
            }[];
            /** Menu Url */
            menu_url?: string | null;
            /** Website */
            website?: string | null;
            /** Google Maps Url */
            google_maps_url?: string | null;
            /** Review Summary */
            review_summary?: {
                [key: string]: unknown;
            } | null;
        };
        /** RestaurantDetailResponse */
        RestaurantDetailResponse: {
            data: components["schemas"]["RestaurantDetailData"];
        };
        /** SaveFavoriteRequest */
        SaveFavoriteRequest: {
            /**
             * Item Type
             * @description restaurant | dish
             */
            item_type: string;
            /** Item Id */
            item_id: string;
            /**
             * Name
             * @description Tên để hiển thị trong danh sách đã lưu, chụp lại lúc lưu.
             */
            name: string;
        };
        /** SavedItemResponse */
        SavedItemResponse: {
            data: components["schemas"]["SavedItemSchema"];
        };
        /** SavedItemSchema */
        SavedItemSchema: {
            /**
             * Item Type
             * @description restaurant | dish
             */
            item_type: string;
            /** Item Id */
            item_id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at?: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Session Id
             * @description UUID v4 do client tự sinh và lưu ở localStorage. VẪN BẮT BUỘC dù đã có tài khoản (2026-08-17): nó định danh một LƯỢT DÙNG, còn tài khoản định danh một NGƯỜI. Việc gắn `user_id` vào tương tác là bước riêng, chưa làm.
             */
            session_id: string;
            /**
             * Latitude
             * @default 21.0285
             */
            latitude: number;
            /**
             * Longitude
             * @default 105.8542
             */
            longitude: number;
            /**
             * Query Text
             * @description Nhu cầu bằng câu tự nhiên, VD "quán lẩu ấm cúng gần đây".
             */
            query_text?: string | null;
            /**
             * Mood
             * @description Lối tắt tuỳ chọn thay cho query_text. Hợp lệ: ['happy', 'sad', 'excited', 'relaxed']
             */
            mood?: string | null;
            /**
             * Max Distance Km
             * @description null = tắt lọc theo khoảng cách.
             * @default 10
             */
            max_distance_km: number | null;
            /**
             * Dietary Restrictions
             * @description vegetarian | vegan | halal | kosher | gluten_free. Dữ liệu rất thưa - quán chưa khai báo vẫn được giữ lại.
             */
            dietary_restrictions?: string[];
            /**
             * Opening Hours Constraint
             * @description "now" hoặc "HH:mm". Quán chưa có dữ liệu giờ vẫn giữ lại.
             */
            opening_hours_constraint?: string | null;
            /**
             * District
             * @description Đơn vị hành chính, VD "Phường Cầu Giấy". Không khớp quán nào -> bỏ lọc.
             */
            district?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** SearchResponse */
        SearchResponse: {
            data: components["schemas"]["SearchResponseData"];
        };
        /** SearchResponseData */
        SearchResponseData: {
            /** Search Query Id */
            search_query_id: string;
            /** Results */
            results: components["schemas"]["SearchResultItemSchema"][];
            /**
             * Context
             * @default []
             */
            context: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** SearchResultItemSchema */
        SearchResultItemSchema: {
            /** Restaurant Id */
            restaurant_id: string | null;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance M */
            distance_m: number;
            /** Price Range */
            price_range: string | null;
            /** Rating */
            rating: number | null;
            /** User Ratings Total */
            user_ratings_total: number | null;
            /** Rank Position */
            rank_position: number;
            /** Predicted Score */
            predicted_score: number;
            /** Match Source */
            match_source: string;
            /**
             * Thumbnail Url
             * @description Ảnh đại diện. null = chưa có ảnh (78.5% quán)
             */
            thumbnail_url?: string | null;
            /** District */
            district?: string | null;
            /**
             * Dietary
             * @default []
             */
            dietary: string[];
            /**
             * Amenities
             * @default []
             */
            amenities: string[];
            /** Source */
            source?: string | null;
            /** Experience Cluster Id */
            experience_cluster_id?: number | null;
            /** Experience Cluster Label */
            experience_cluster_label?: string | null;
            /** Temporarily Closed */
            temporarily_closed?: boolean | null;
            /** Source Updated At */
            source_updated_at?: string | null;
            /** Source Datasets */
            source_datasets?: string[];
            /** Surveyed At */
            surveyed_at?: string | null;
            suggested_dish?: components["schemas"]["SuggestedDishSchema"] | null;
        };
        /** SuggestedDishSchema */
        SuggestedDishSchema: {
            /** Dish Id */
            dish_id: string;
            /** Name */
            name: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Spice Level */
            spice_level?: number | null;
            /** Temperature */
            temperature?: string | null;
            /** Confidence */
            confidence: string;
            /** Reason */
            reason?: string | null;
        };
        /**
         * UserPublic
         * @description Bản công khai của một tài khoản. KHÔNG BAO GIỜ chứa `password_hash`.
         */
        UserPublic: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /**
             * Role
             * @description user | admin
             */
            role: string;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * UserSelf
         * @description Bản hồ sơ CHÍNH CHỦ nhìn thấy — có thêm email và ngày tham gia.
         *
         *     Kế thừa UserPublic để hai bên không lệch nhau khi thêm trường mới.
         */
        UserSelf: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /**
             * Role
             * @description user | admin
             */
            role: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Email
             * @description Chỉ chính chủ thấy. Không lộ cho người khác.
             */
            email?: string | null;
            /**
             * Created At
             * @description Ngày tạo tài khoản, dạng ISO-8601.
             */
            created_at?: string | null;
        };
        /**
         * UserStatsData
         * @description Số liệu hoạt động của chính chủ.
         *
         *     `explorations` = số QUÁN KHÁC NHAU đã mở xem đủ lâu. Định nghĩa hẹp và cố ý — xem
         *     `domain/services/gamification.py`.
         */
        UserStatsData: {
            /** Saved Restaurants */
            saved_restaurants: number;
            /** Saved Dishes */
            saved_dishes: number;
            /** Viewed Restaurants */
            viewed_restaurants: number;
            /** Explorations */
            explorations: number;
            /** Directions */
            directions: number;
            /** Ratings */
            ratings: number;
            /** Closure Reports */
            closure_reports: number;
            /** Active Days */
            active_days: number;
            /** Points */
            points: number;
            level: components["schemas"]["LevelProgressSchema"];
            /** Badges */
            badges: components["schemas"]["BadgeSchema"][];
        };
        /** UserStatsResponse */
        UserStatsResponse: {
            data: components["schemas"]["UserStatsData"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    suggest_dishes_api_v1_dishes_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishSuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishSuggestResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    dish_detail_api_v1_dishes__dish_id__get: {
        parameters: {
            query?: {
                latitude?: number;
                longitude?: number;
                max_distance_km?: number;
            };
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishDetailResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    restaurants_for_dish_api_v1_dishes__dish_id__restaurants_get: {
        parameters: {
            query: {
                session_id: string;
                latitude?: number;
                longitude?: number;
                max_distance_km?: number;
                mood?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    restaurant_detail_api_v1_restaurants__restaurant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantDetailResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    log_interaction_api_v1_interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    moods_api_v1_moods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoodsResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_favorites_api_v1_me_favorites_get: {
        parameters: {
            query?: {
                /** @description Lọc theo loại: restaurant | dish. Bỏ trống = cả hai. */
                item_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    save_favorite_api_v1_me_favorites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFavoriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedItemResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    remove_favorite_api_v1_me_favorites__item_type___item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_type: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    user_stats_api_v1_me_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsResponse"];
                };
            };
            /** @description INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESTAURANT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description DATA_NOT_READY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_restaurants_api_v1_admin_restaurants_get: {
        parameters: {
            query?: {
                /** @description Lọc theo tên, địa chỉ hoặc placeId */
                q?: string | null;
                limit?: number;
                /** @description Có kèm quán đã ẩn hay không */
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_restaurant_api_v1_admin_restaurants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateRestaurantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_restaurant_api_v1_admin_restaurants__restaurant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateRestaurantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_restaurant_api_v1_admin_restaurants__restaurant_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_restaurant_api_v1_admin_restaurants__restaurant_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
